import type { Metadata } from "next";
import localFont from "next/font/local";
import { Nav } from "./_components/nav/Nav";
import "./globals.css";

export const pretendard = localFont({
  src: [
    {
      path: "../public/fonts/PretendardThin.otf",
      weight: "100",
      style: "normal",
    },
    {
      path: "../public/fonts/PretendardExtraLight.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../public/fonts/PretendardLight.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/PretendardRegular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/PretendardMedium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/PretendardSemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/PretendardBold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/PretendardExtraBold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/PretendardBlack.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "The Artist Canvas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Nav />
        {children}
      </body>
    </html>
  );
}
